version: '3'

services:
  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Здесь вы можете указать порты, на которых ваше приложение работает
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production  # Установите нужные переменные окружения
